source = $HOME/.config/hypr/colors.conf

$accent = $mauve
$accentAlpha = $mauveAlpha
$font = Ubuntu Nerd Font Propo

# Geral
general {
  hide_cursor = true
}

# Plano de Fundo
background {
  monitor =
  path = $HOME/.config/hypr/.hyprlock
  color = $base
  blur_passes = 0
}

# Fumê
shape {
  monitor =
  size = 600, 80%
  color = rgba($crustAlpha99)
  rounding = 16
  position = 0, 0
}

# Teclado
label {
  monitor =
  text = Layout: $LAYOUT
  color = $text
  font_size = 12
  font_family = $font
  position = 0, 32
  valign = bottom
}

# Horas
label {
  monitor =
  text = cmd[update:1000] echo "<b>$(date +"%Hh%M")</b>"
  color = $text
  font_size = 112
  font_family = $font
  position = 0, -128
  valign = top
}

# Data
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d de %B de %Y" | sed 's/.*/\u&/'
  color = $text
  font_size = 20
  font_family = $font
  position = 0, -304
  valign = top
}

# Digital
{
  monitor = 
  text = $FPRINTPROMPT
  color = $text
  font_size = 14
  font_family = $font
  position = 0, -107
}

# Avatar
image {
  monitor =
  path = $HOME/.face
  size = 160
  rounding = 32
  border_color = $accent
  border_size = 2
}

# Nome do Usuário
label {
  monitor =
  text = <b>$USER</b>
  color = $text
  font_size = 16
  font_family = $font
  position = 0, -128
}

# Senha
input-field {
  monitor =
  size = 320, 48
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $surface0
  font_color = $text
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾  Senha</i></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -176
}

# Música Atual
label {
  monitor =
  text = cmd[update:1000] echo "<b>$($HOME/.config/hypr/scripts/current-song.sh)</b>"
  color = $green
  font_size = 12
  font_family = $font
  position = 0, 144
  valign = bottom
}